### ISSUE TITLE
New release, please

### ISSUE THREAD

**Issue by pysailor** [collective/collective.workspace#17]
Hi,
the last release on pypi is almost 2 years old. And in the meantime, important goodies like caching have been added. Therefore, can we please have a new release?
It would also be fine if you give access on pypi to one or more of the following people, and we will cut the new release:
* @gyst (pypi: guidostevens)
* @pilz (pypi: pilz)
* @ale-rt (pypi: alert)
* or me (pypi: thomasw)

**Comment by mattss** [comment]
@pysailor I've just given you pypi maintainer access on collective.workspace.

**Comment by davisagli** [comment]
Looks like this was done.

By the way, I am going to take another look at my `native-groups` branch today and see if I can figure out how to get it merged. If that happens it will become a 2.0 release.
