### ISSUE TITLE
Should migration include auto groups?

### ISSUE THREAD

**Issue by ale-rt** [collective/collective.workspace#27]
I do not see why here:
https://github.com/collective/collective.workspace/blob/bc31d80dd21c93f973a21244e8aa02bc6e063698/src/collective/workspace/setuphandlers.py#L50
`_update_groups` is called with the parameter `add_auto_groups=False`.
This it seems to always turn off the "Member" group here:
https://github.com/collective/collective.workspace/blob/bc31d80dd21c93f973a21244e8aa02bc6e063698/src/collective/workspace/membership.py#L101-L104

**Comment by davisagli** [comment]
Hmm, I don't remember why I did it that way. It also now seems to me like we should be applying the auto groups here, and that we should not hardcode adding the Members group.

**Comment by ale-rt** [comment]
Yes, infact calling  m._update_groups(set(), set()) after line 50 in the upgrade step will fix the migration.

Another possible way is to handle the migration calling `add_to_team` with the existing data, something like this:
```python
    for user, data in obj._team.iteritems(): 
            if data.get('groups'):
                data['groups'] = set(data['groups'])
            data = data.copy()
            data.pop('user', None); 
            IWorkspace(obj).add_to_team(user, **data)
```

**Comment by davisagli** [comment]
I intentionally avoided using `add_to_team` and `update` because I didn't want to trigger TeamMemberModifiedEvent events during the upgrade.

I think I've fixed the migration in the `27-fix-update-groups-davisagli` branch, since `_update_groups` now updates the membership's `__dict__['groups']` before calculating the auto groups.
