### ISSUE TITLE
Can this be made to work with ATFolder?

### ISSUE THREAD

**Issue by sureshvv** [collective/collective.workspace#7]
For Plone 4.3

**Comment by davisagli** [comment]
You obviously can't use the behavior with an Archetypes-based content type, but you can write your own workspace adapter and it will work. I've done so with the ATContentTypes event content type to handle event registration.

**Comment by sureshvv** [comment]
Great. There is some sample code to write an adapter on the README file.
from collective.workspace.workspace import Workspace

    class MyWorkspace(Workspace):
        """
        A custom workspace behaviour, based on collective.workspace
        """
        # A list of groups to which team members can be assigned.
        # Maps group name -> roles
        available_groups = {
            u'Supervillians': ('Reader', ),
            u'Superheroes': ('Reader', 'Contributor', 'Reviewer', 'Editor',),
        }

Is this enough? Or does anything special need to be done inside the adapter. Any pointers/sample code appreciated.

**Comment by davisagli** [comment]
Yeah, I think that's all you need to do. If you don't specify `available_groups` in your workspace adapter you'll inherit the default ones from the Workspace base class (Members and Admins).

If you want to add custom fields for each member of the roster, you can do that like this:

```
from collective.workspace.membership import ITeamMembership
from collective.workspace.membership import TeamMembership
from collective.workspace.workspace import Workspace
from zope import schema

class IFolderMembership(ITeamMembership):
    notes = schema.Text(title=u'Notes', required=False)

class FolderMembership(TeamMembership):
    _schema = IFolderMembership

class FolderWorkspace(Workspace):  # this is the same as MyWorkspace in the example above
    membership_schema = IFolderMembership
    membership_factory = FolderMembership
```

You can also implement `handle_added`, `handle_modified` and `handle_removed` callbacks on the Membership class if you need to perform custom logic when members are added, updated, or removed.

**Comment by sureshvv** [comment]
Thanks David, for your response and all your contributions to Open source and Plone.
